### ISSUE TITLE
Error when editing unpublished post

### ISSUE THREAD

**Issue by AthmanZiri** [bmwasaru/mentorme#8]
Exception Type: TypeError at /articles/edit/1/
Exception Value: dispatch() got an unexpected keyword argument 'pk'

**Comment by bmwasaru** [comment]
Working on this...I didn't add args and kwargs to the [https://github.com/Mentor001/platform/blob/63797f99e1ecb207d8ec5aec1df423fea6f4fee8/articles/decorators.py#L9](url)

**Comment by AthmanZiri** [comment]
It's fixed. Thanks @bmwasaru
